FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential libffi-dev

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1

COPY . .

EXPOSE 5000

# Run Flask app
CMD ["flask", "run", "debug=True", "--host=0.0.0.0", "--port=5000"]