name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Deploy via SSH'
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd Fairness-Chatbot/api

          # Pull latest code
          git pull origin main

          # Remove old container
          docker stop fairness-backend || true
          docker rm -f fairness-backend || true

          docker image prune -f

          # Build and run new container
          docker build -f Dockerfile.backend -t fairness-backend .
          docker run -d \
            --restart=always \
            --name fairness-backend \
            -p 5000:5000 \
            --env-file .env \
            --memory=1.2g \
            fairness-backend:latest