name: Keep Supabase Alive

on:
  schedule:
    #Runs every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch: 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          echo "Pinging Supabase..."
          curl -s -o /dev/null -w "%{http_code}\n" "$SUPABASE_URI/auth/v1/health"
        env:
          SUPABASE_URI: ${{ secrets.SUPABASE_URI }}
